name: Pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings ./Xyaneon.Bioinformatics.FASTA.Test/coverlet.runsettings

    # Workaround for issue: https://github.com/microsoft/vstest/issues/2378
    - name: Relocate test coverage results
      run: mv ./Xyaneon.Bioinformatics.FASTA.Test/TestResults/**/coverage.info ./Xyaneon.Bioinformatics.FASTA.Test/TestResults/

    - name: Upload coverage file to Coveralls.io
      uses: coverallsapp/github-action@v2.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Xyaneon.Bioinformatics.FASTA.Test/TestResults/coverage.info
        format: lcov
